repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1 # whatever you use
    hooks:
      - id: mypy
        args: ["--explicit-package-bases"]
        additional_dependencies:
          - types-PyYAML
          - types-Jinja2
          - PyYAML
          - Jinja2