[project]
name = "ml-project-foundations-data-quarry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.12.0",
    "dvc>=3.66.1",
    "mypy>=1.19.1",
    "platformdirs>=4.5.1",
    "ruff>=0.14.13",
    "tomli-w>=1.2.0",
    "typer>=0.21.1",
]

[project.scripts]
data-repo-setup = "data_repo_setup.cli:app"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
